[pytest]
# Stop after 2 failures
addopts = --maxfail=2 -v --html=reports/report.html --self-contained-html --log-cli-level=INFO --capture=tee-sys

# Enable live logging during test run
log_cli = true
log_cli_level = INFO

# Optional: format log messages
log_format = %(asctime)s [%(levelname)s] %(message)s
log_date_format = %Y-%m-%d %H:%M:%S